In [7]:
import numpy as np

In [8]:
a = np.array([0, 1, 2, 3])
a

array([0, 1, 2, 3])

In [13]:
b = np.arange(-1, 1, 0.01)
b

array([-1.0000000e+00, -9.9000000e-01, -9.8000000e-01, -9.7000000e-01,
       -9.6000000e-01, -9.5000000e-01, -9.4000000e-01, -9.3000000e-01,
       -9.2000000e-01, -9.1000000e-01, -9.0000000e-01, -8.9000000e-01,
       -8.8000000e-01, -8.7000000e-01, -8.6000000e-01, -8.5000000e-01,
       -8.4000000e-01, -8.3000000e-01, -8.2000000e-01, -8.1000000e-01,
       -8.0000000e-01, -7.9000000e-01, -7.8000000e-01, -7.7000000e-01,
       -7.6000000e-01, -7.5000000e-01, -7.4000000e-01, -7.3000000e-01,
       -7.2000000e-01, -7.1000000e-01, -7.0000000e-01, -6.9000000e-01,
       -6.8000000e-01, -6.7000000e-01, -6.6000000e-01, -6.5000000e-01,
       -6.4000000e-01, -6.3000000e-01, -6.2000000e-01, -6.1000000e-01,
       -6.0000000e-01, -5.9000000e-01, -5.8000000e-01, -5.7000000e-01,
       -5.6000000e-01, -5.5000000e-01, -5.4000000e-01, -5.3000000e-01,
       -5.2000000e-01, -5.1000000e-01, -5.0000000e-01, -4.9000000e-01,
       -4.8000000e-01, -4.7000000e-01, -4.6000000e-01, -4.5000000e-01,
      

In [16]:
np.linspace(1, 10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [21]:
M = np.array([[1, 2], [3, 4]])
M, M.dtype

(array([[1, 2],
        [3, 4]]),
 dtype('int32'))

In [22]:
a = np.arange(10)
a

array([0, 2, 4, 6, 8])

In [23]:
b = a.copy()
b[0] = 10
a, b

(array([0, 2, 4, 6, 8]), array([10,  2,  4,  6,  8]))

In [29]:
np.concatenate((a, b.T), axis=0)

array([ 0,  2,  4,  6,  8, 10,  2,  4,  6,  8])

In [39]:
c = np.diag(np.array([1, 2, 3, 4]))
c

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [41]:
c[::-1]

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [42]:
M = np.random.randint(1, 100, size=(4, 4))
M

array([[41, 90, 35, 76],
       [86,  7, 29, 20],
       [95, 90, 35, 85],
       [78, 55, 93, 47]])

In [48]:
M[1:4, 1:4]

array([[ 7, 29, 20],
       [90, 35, 85],
       [55, 93, 47]])

In [49]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])

In [50]:
a > b

array([False, False,  True, False])

In [51]:
a >= b

array([False,  True,  True,  True])

In [52]:
a == b

array([False,  True, False,  True])